-- Admin user seed
-- Replace ${ADMIN_PASSWORD_HASH} with a hash generated by ASU PasswordHasher

INSERT INTO users
(
    username,
    password_hash,
    email,
    role,
    status
)
VALUES
(
    'admin',
    '${ADMIN_PASSWORD_HASH}',
    'admin@asu.local',
    'admin',
    'active'
);
