-- Initial administrator seed
-- Password hash must be generated by ASU Authentication layer.

INSERT INTO users (
    username,
    email,
    password_hash,
    role,
    status
) VALUES (
    'admin',
    'admin@asu.local',
    'REPLACE_WITH_GENERATED_HASH',
    'administrator',
    'active'
);
